{% set name = "lfdfiles" %}
{% set version = "2023.4.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lfdfiles-{{ version }}.tar.gz
  sha256: b1d08eeccc5dff9f9d87cabe5f44ed0d93be455a235899809de74648f61fdab0

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - lfdfiles=lfdfiles.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - cython >=0.29.27
    - numpy >=1.21.5
    - pip
    - python
    - setuptools >=18.0
  run:
    - click
    - czifile >=2019.7.2
    - matplotlib-base >=3.4.3
    - netpbmfile >=2021.6.6
    - {{ pin_compatible('numpy') }}
    - oiffile >=2021.6.6
    - python
    - tifffile >=2021.11.2

test:
  imports:
    - lfdfiles
  commands:
    - pip list
    - pip check
    - lfdfiles --help
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Laboratory for Fluorescence Dynamics (LFD) file formats
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/lfdfiles/

extra:
  recipe-maintainers:
    - goanpeca
